### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by mikejestes**
Initial Review:

**Product Info Caching / Data Issues**
With all 3 price issues I feel like something is getting cached. When I save the product form, these values should update. I made an initial request and then updated the product and wasn't able to see new values.
- [x] Use Manufacturer's Suggested Retail Price as our `regular_price`
- [x] ~~When an active Special Price is set, use that for `retail_price`~~
- [x] ~~Cost doesn’t seem to show up.~~

**Other**
- [x] remove `button` field from `PriceWaiterOptions` so it doesn’t overwrite settings coming down from API / widget.js
- [x] Can you generate a token for `product_data_secret` and pass that with the `product_data_url` to the store signup API?
- [x] ~~The product_configuration metadata is a bit long (we should hide these in the UI). Can that be broken into individual fields? Seems that the product info controller is mostly needing the product_id var?~~
- [x] rename `product_configuration` metafield to `_magento_product_configuration`
- [x] On page JavaScript should send the configured product's SKU instead of the configurable product's SKU.
- [ ] Generate tar file with version 2.0.0?

### CODE REVIEW

**Comment by mikejestes** [comment]
The platform info API support is now on staging, both for store sign up fields, and actually querying data.

**Comment by bobbyburden** [comment]
@mikejestes:
For the pricing issues, make sure you are clearing the Magento cache and re-indexing.
On the cost, do you have a cost associated with your test product?

**Comment by mikejestes** [comment]
My VM is super slow but I tried running:

```
mage cache:disable
mage cache:clean
mage cache:flush
mage index:reindex:all
```

Product:
screen shot 2015-02-27 at 10 53 55 am

` curl -X POST --data 'product_configuration=form_key%3DKSbkykE4JZotR01L%26product%3D425%26related_product%3D%26super_attribute%255B92%255D%3D27%26super_attribute%255B180%255D%3D74%26qty%3D1&store_id=1161&product_sku=wsd013c' -H 'X-PriceWaiter-Signature: sha256=b56c27c324641b8578b5d9ad6782cbb00b50bf1478c9a5a73b8d716be28657fd' https://64e279ba.ngrok.com/pricewaiter/productinfo`

```json
{
    "allow_pricewaiter": true,
    "inventory": 13,
    "can_backorder": false,
    "retail_price": "340",
    "retail_price_currency": "USD",
    "regular_price": "340.0000",
    "regular_price_currency": "USD"
}
```

**Comment by mikejestes** [comment]
Is the form_key making it stick to some old cart row that has old data?

My reindex never finished after 2 hours.

**Comment by bobbyburden** [comment]
I don't believe the `form_key` is the issue.

If your reindex never finished, I'm almost sure that's still a problem

**Comment by mikejestes** [comment]
Nevermind, that was a configurable product.

I think the MSRP is not being factored in:

screen shot 2015-02-27 at 1 39 02 pm


```json
{
  "inventory": { "known": true, "stock": 25, "can_backorder": false, "timestamp": 1425073108 },
  "cost": { "known": true, "amount": 9000, "currency": "USD", "timestamp": 1425073108 },
  "retail_price": { "known": true, "amount": 12000, "currency": "USD", "timestamp": 1425073108 },
  "regular_price": { "known": true, "amount": 15000, "currency": "USD", "timestamp": 1425073108 }
}
```

**Comment by bobbyburden** [comment]
I added a Cakefile to compile the CoffeeScript. Make sure to run that before testing the on-page JavaScript.

**Comment by mikejestes** [comment]
:+1: :clap: :fireworks: 

@bobbyburden can you merge PR, build a 2.0.0 tar and install on magentodemo?

**Comment by bobbyburden** [comment]
@mikejestes Yep

**Pull request merged**
